version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "your-github-username"
    reviewers:
      - "your-github-username"
    
  # npm packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "your-github-username"
    reviewers:
      - "your-github-username"
    groups:
      development-dependencies:
        patterns:
          - "@types/*"
          - "vitest*"
          - "playwright*"
          - "eslint*"
          - "prettier*"
      production-dependencies:
        patterns:
          - "next"
          - "react"
          - "@ai-sdk/*"
          - "drizzle-orm"