name: Status Badges

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  push:
    branches: [main]

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate badge data
        run: |
          # Create badge data directory
          mkdir -p .github/badges
          
          # CI status based on workflow run
          if [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
            echo '{"schemaVersion": 1, "label": "CI", "message": "passing", "color": "brightgreen"}' > .github/badges/ci.json
            echo '{"schemaVersion": 1, "label": "build", "message": "passing", "color": "brightgreen"}' > .github/badges/build.json
          else
            echo '{"schemaVersion": 1, "label": "CI", "message": "failing", "color": "red"}' > .github/badges/ci.json
            echo '{"schemaVersion": 1, "label": "build", "message": "failing", "color": "red"}' > .github/badges/build.json
          fi
          
          # TypeScript status
          echo '{"schemaVersion": 1, "label": "TypeScript", "message": "strict", "color": "blue"}' > .github/badges/typescript.json
          
          # Dependencies status  
          echo '{"schemaVersion": 1, "label": "dependencies", "message": "up to date", "color": "brightgreen"}' > .github/badges/dependencies.json
      
      - name: Commit badge data
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .github/badges
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update status badges"
          git push